### ISSUE TITLE
Fix inconsistencies

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/website#88]
Things we can improve on the mirror page:

- [x] Highlight the GMT ftp master the same way we do for the data server master.  Maybe a more watered-down pastel color for both? (#91)
- [x] Change the uppercase country names in the ftp listing to lower case, as for data servers (#90)
- [x] Have a leading paragraph right after the page title where we acknowledge and thank the institutions for hosting, rather than repeating this twice and differently for the two sets. (#91)
- [x] Use USA, not US for that country (#90)
- [x] Replace _europe_ with _portugal_ in the forwards and then here (but leave _europe_ as a 2nd hover forwards for now). (#89)
